name: React CI - Test and Docker Build (with latest tag)

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with 'latest' and SHA tags
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}
